
$mainMod2 = SUPER
$mainMod = ALT


# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                         Source Files                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
source = ~/.config/nordix/system/color/colors.conf
source = /usr/share/nordix/yggdrasil/config/system-windowrules.conf
source = ~/.config/nordix/desktop/config/nordix-environment.conf
source = ~/.config/nordix/desktop/config/nordix-monitors.conf
source = ~/.config/nordix/system/animations/animations.conf
source = ~/.config/hypr/config/nordix-decorations.conf

source = ~/.config/nordix/desktop/config/nordix-advanced.conf
source = ~/.config/nordix/desktop/config/nordix-general.conf
source = ~/.config/nordix/desktop/config/nordix-groups.conf
source = ~/.config/nordix/desktop/config/nordix-input.conf
source = ~/.config/nordix/desktop/config/nordix-layout.conf
source = ~/.config/nordix/system/keybinds/keybinds.conf
source = ~/.config/nordix/system/windowrules/windowrules.conf
source = ~/.config/hypr/config/defaults.conf
source = ~/.config/hypr/config/autostart.conf 

 xwayland {
   force_zero_scaling = true       # Unscale XWayland
 }
